# frozen_string_literal: true

module CamWheel
  SETTINGS_NAMESPACE = PLUGIN_NAME.dup.freeze
  DEFAULT_COMPOSITION_RATIO_LANDSCAPE = "4:3".freeze
  DEFAULT_COMPOSITION_RATIO_PORTRAIT = "3:4".freeze
  DEFAULT_COMPOSITION_STYLE = "rule_of_thirds".freeze
  DEFAULT_COMPOSITION_VCB_INPUT_MODE = "fov".freeze
  DEFAULT_FREE_RATIO_WIDTH = 4.0
  DEFAULT_FREE_RATIO_HEIGHT = 3.0
  DEFAULT_LINE_COLOR = "#00FF66".freeze
  DEFAULT_LINE_WIDTH = 1.0
  DEFAULT_MASK_COLOR = "#000000".freeze
  DEFAULT_MASK_ALPHA = 0.45
  DEFAULT_PENETRATION_OFFSET = 100.0
  DEFAULT_OVERLAY_SHOW_LABEL = true
  DEFAULT_SPIRAL_CORNER = "top_left".freeze
end
